package lean2kotlin

import java.nio.file.Files
import java.nio.file.Path

const val GENERATED_HEADER = "// GENERATED by lean2kotlin — DO NOT EDIT"

/**
 * 生成ファイルの書き出し。役割ごとのサブパッケージ = サブディレクトリに配置する。
 * - すべてのファイルは GENERATED ヘッダで始まる。
 * - 出力ディレクトリの掃除は「GENERATED ヘッダを持つ .kt だけを消す」—
 *   誤設定で手書きコードを消さないための安全弁。
 */
class Output(private val dir: Path, val basePackage: String, private val indent: String) {
	private val written = mutableListOf<Path>()

	fun cleanGenerated() {
		if (!Files.exists(dir)) return
		Files.walk(dir).use { stream ->
			stream.filter { it.toString().endsWith(".kt") && Files.isRegularFile(it) }
				.filter { p ->
					Files.newBufferedReader(p).use { r -> r.readLine()?.startsWith(GENERATED_HEADER) == true }
				}
				.forEach { Files.delete(it) }
		}
		// 空になったディレクトリを片付ける(深い順)
		Files.walk(dir).use { stream ->
			stream.sorted(Comparator.reverseOrder())
				.filter { it != dir && Files.isDirectory(it) }
				.filter { p -> Files.list(p).use { it.findFirst().isEmpty } }
				.forEach { Files.delete(it) }
		}
	}

	/**
	 * 1 ファイル書き出し。subpkg が役割別サブパッケージ(null はルート)。
	 * body はインデントをタブ 1 文字 = "\t" で書いたものを渡し、
	 * ここで設定のインデント文字列に置換する。
	 */
	fun file(subpkg: String?, name: String, imports: List<String> = emptyList(), body: String) {
		val pkg = if (subpkg == null) basePackage else "$basePackage.$subpkg"
		val sb = StringBuilder()
		sb.append(GENERATED_HEADER).append('\n')
		sb.append("// 再生成で全上書きされます。実装はこのファイルではなく別ファイルに書いてください。\n\n")
		sb.append("package ").append(pkg).append("\n\n")
		if (imports.isNotEmpty()) {
			imports.sorted().distinct().forEach { sb.append("import ").append(it).append('\n') }
			sb.append('\n')
		}
		sb.append(reindent(body.trimEnd()) ).append('\n')
		val target = if (subpkg == null) dir else dir.resolve(subpkg.replace('.', '/'))
		val path = target.resolve("$name.kt")
		// 同じパスへの 2 回目の書き出しは先の生成物を黙って消す — 名前の衝突は生成の失敗にする。
		// 大文字小文字だけ違うパスも衝突 — 生成物はコミットされ、区別しないファイルシステム(macOS の既定)にも展開される
		val clash = written.find { it.toString().equals(path.toString(), ignoreCase = true) }
		check(clash == null) {
			if (clash == path) "生成物の出力先が衝突しています(同じファイルを 2 回書こうとした): $path"
			else "生成物の出力先が衝突しています(大文字小文字だけ違うファイル — 区別しないファイルシステムで上書きになる): $clash と $path"
		}
		Files.createDirectories(path.parent)
		Files.writeString(path, sb.toString())
		written.add(path)
	}

	private fun reindent(s: String): String =
		if (indent == "\t") s
		else s.lines().joinToString("\n") { line ->
			var i = 0
			while (i < line.length && line[i] == '\t') i++
			indent.repeat(i) + line.substring(i)
		}

	fun report(): List<Path> = written.toList()
}
