package lean2kotlin.gradle

import lean2kotlin.Lean2KotlinGeneration
import org.gradle.api.DefaultTask
import org.gradle.api.Plugin
import org.gradle.api.Project
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.file.SourceDirectorySet
import org.gradle.api.provider.Property
import org.gradle.api.tasks.*
import org.gradle.api.plugins.ExtensionAware
import org.gradle.api.file.ConfigurableFileCollection
import org.gradle.process.ExecOperations
import javax.inject.Inject

/** build.gradle.kts の lean2kotlin { } 設定。 */
abstract class Lean2KotlinExtension {
	/** 抽出済み IR(#kotlin_ir の出力 JSON)。 */
	abstract val irFile: RegularFileProperty
	/** 生成する Kotlin のベースパッケージ。 */
	abstract val kotlinPackage: Property<String>
	/** golden ディレクトリ(参照系の golden 回帰と Retrieve テストの源。省略時はその分のケースを生成しない)。 */
	abstract val goldenDir: DirectoryProperty
	/** 生成先(既定: src/generated/kotlin-main / kotlin-test)。 */
	abstract val mainOut: DirectoryProperty
	abstract val testOut: DirectoryProperty
	/** インデント(既定: タブ)。 */
	abstract val indent: Property<String>
	/** 生成ディレクトリを sourceSets に自動配線するか(既定: true)。 */
	abstract val wireSourceSets: Property<Boolean>

	/** 対象 Lean モデルの root 名前空間(例: "Sprout")。指定すると extractLeanIr が
	    有効になり、ドライバ(.lean)は plugin が合成する — 手書きのドライバは不要。 */
	abstract val leanRootNamespace: Property<String>
	/** binder 上書き(Runtime に表現を置かない型引数の単型化。例: "Name" to "String")。 */
	abstract val binderOverrides: org.gradle.api.provider.MapProperty<String, String>
	/** 抽出器の lake パッケージ(lean2kotlin リポジトリの lean/)。ワークスペースは
	    build/lean2kotlin/workspace に合成され、leanDomainDir の require が
	    抽出器側の推移的 require を上書きする — どの checkout の domain を読むかは
	    常に leanDomainDir が決める。 */
	abstract val leanExtractorDir: DirectoryProperty
	/** 対象ドメインの lake パッケージ。抽出前に lake build する
	    (lake env はビルドしないため、これがないと古い olean を読む)。 */
	abstract val leanDomainDir: DirectoryProperty
	/** lake コマンド(既定: "lake" — elan の PATH 前提)。 */
	abstract val lakeCommand: Property<String>
}

/** 抽出: ドライバ(#kotlin_ir)を設定から合成し、対象ドメインを lake build してから実行。 */
abstract class ExtractLeanIrTask : DefaultTask() {
	@get:Inject
	abstract val execOps: ExecOperations

	@get:Input
	abstract val rootNamespace: Property<String>

	@get:Input
	abstract val binderOverrides: org.gradle.api.provider.MapProperty<String, String>

	@get:Internal
	abstract val workspaceDir: DirectoryProperty

	@get:Internal
	abstract val leanExtractorDir: DirectoryProperty

	@get:Internal
	abstract val leanDomainDir: DirectoryProperty

	/** up-to-date 判定用: ドメインと抽出側の Lean ソース。 */
	@get:InputFiles
	@get:PathSensitive(PathSensitivity.RELATIVE)
	abstract val leanSources: ConfigurableFileCollection

	@get:Input
	abstract val lakeCommand: Property<String>

	@get:OutputFile
	abstract val irFile: RegularFileProperty

	@TaskAction
	fun run() {
		val lake = lakeCommand.get()
		val ns = rootNamespace.get()
		val domain = leanDomainDir.get().asFile
		val extractor = leanExtractorDir.get().asFile

		// ワークスペースの合成: root の require が抽出器側の推移的 require(同名)を
		// 上書きするため、どの checkout の domain を読むかは leanDomainDir が決める
		val ws = workspaceDir.get().asFile
		ws.mkdirs()
		val domainLakefile = domain.resolve("lakefile.toml")
		val domainName = Regex("^name\\s*=\\s*\"([^\"]+)\"", RegexOption.MULTILINE)
			.find(domainLakefile.readText())?.groupValues?.get(1)
			?: error("対象ドメインのパッケージ名を読めません: $domainLakefile")
		val lakefileText =
			"# GENERATED by lean2kotlin plugin — 抽出ワークスペース(設定から合成)\n" +
			"name = \"lean2kotlin-extraction\"\n\n" +
			"[[require]]\nname = \"$domainName\"\npath = \"${domain.absolutePath}\"\n\n" +
			"[[require]]\nname = \"lean2kotlin\"\npath = \"${extractor.absolutePath}\"\n"
		val lakefile = ws.resolve("lakefile.toml")
		if (!lakefile.exists() || lakefile.readText() != lakefileText) {
			// 依存の結線が変わった — 古い解決(manifest)を捨てて作り直す
			ws.resolve("lake-manifest.json").delete()
		}
		lakefile.writeText(lakefileText)
		ws.resolve("lean-toolchain").writeText(domain.resolve("lean-toolchain").readText())
		val out = irFile.get().asFile.absolutePath
		val binds = binderOverrides.get().entries
			.sortedBy { it.key }
			.joinToString("") { "\n  \"${it.key}=${it.value}\"" }
		val driver = ws.resolve("Driver.lean")
		driver.writeText(
			"-- GENERATED by lean2kotlin plugin — 設定(build.gradle.kts)から合成される\n" +
			"import $ns\nimport Lean2Kotlin.Extract\n\n" +
			"-- 契約定理の演繹は Lean 内評価(オラクル)を多用する — 既定の上限では足りない\n" +
			"set_option maxHeartbeats 4000000 in\n" +
			"#kotlin_ir \"$ns\" \"$out\"$binds\n")

		logger.lifecycle("lean2kotlin: 抽出 #kotlin_ir \"$ns\"(domain: $domain)")
		if (!ws.resolve("lake-manifest.json").exists()) {
			execOps.exec { it.workingDir(ws); it.commandLine(lake, "update") }
		}
		// lake env はビルドしない — 必要なライブラリ(対象 root と抽出器)を先に build する
		execOps.exec { it.workingDir(ws); it.commandLine(lake, "build", ns, "Lean2Kotlin") }
		execOps.exec { it.workingDir(ws); it.commandLine(lake, "env", "lean", driver.absolutePath) }
		require(irFile.get().asFile.exists()) {
			"抽出は成功しましたが IR がありません: ${irFile.get()}"
		}
	}
}

@CacheableTask
abstract class GenerateKotlinFromLeanTask : DefaultTask() {
	@get:InputFile
	@get:PathSensitive(PathSensitivity.NONE)
	abstract val irFile: RegularFileProperty

	@get:InputDirectory
	@get:Optional
	@get:PathSensitive(PathSensitivity.RELATIVE)
	abstract val goldenDir: DirectoryProperty

	@get:Input
	abstract val kotlinPackage: Property<String>

	@get:Input
	abstract val indent: Property<String>

	@get:OutputDirectory
	abstract val mainOut: DirectoryProperty

	@get:OutputDirectory
	abstract val testOut: DirectoryProperty

	@TaskAction
	fun run() {
		Lean2KotlinGeneration.run(
			irPath = irFile.get().asFile.toPath(),
			kotlinPackage = kotlinPackage.get(),
			mainOut = mainOut.get().asFile.toPath(),
			testOut = testOut.get().asFile.toPath(),
			indent = indent.get(),
			goldenDir = goldenDir.orNull?.asFile?.toPath(),
			log = { logger.lifecycle("lean2kotlin: $it") })
	}
}

class Lean2KotlinPlugin : Plugin<Project> {
	override fun apply(project: Project) {
		val ext = project.extensions.create("lean2kotlin", Lean2KotlinExtension::class.java)
		ext.mainOut.convention(project.layout.projectDirectory.dir("src/generated/kotlin-main"))
		ext.testOut.convention(project.layout.projectDirectory.dir("src/generated/kotlin-test"))
		ext.indent.convention("\t")
		ext.wireSourceSets.convention(true)
		// 抽出を plugin が担う場合、IR は build ディレクトリ管理の中間成果物
		ext.irFile.convention(project.layout.buildDirectory.file("lean2kotlin/lean2kotlin-ir.json"))

		val gen = project.tasks.register(
			"generateKotlinFromLean", GenerateKotlinFromLeanTask::class.java) { t ->
			t.group = "lean2kotlin"
			t.description = "Lean ドメインモデルの IR から Kotlin(型・interface・契約テスト)を生成する"
			t.irFile.set(ext.irFile)
			t.goldenDir.set(ext.goldenDir)
			t.kotlinPackage.set(ext.kotlinPackage)
			t.indent.set(ext.indent)
			t.mainOut.set(ext.mainOut)
			t.testOut.set(ext.testOut)
		}

		val extract = project.tasks.register(
			"extractLeanIr", ExtractLeanIrTask::class.java) { t ->
			t.group = "lean2kotlin"
			t.description = "Lean ドメインモデルから IR(JSON)を抽出する(lake build + #kotlin_ir)"
			t.rootNamespace.set(ext.leanRootNamespace)
			t.binderOverrides.set(ext.binderOverrides)
			t.workspaceDir.set(project.layout.buildDirectory.dir("lean2kotlin/workspace"))
			t.leanExtractorDir.set(ext.leanExtractorDir)
			t.leanDomainDir.set(ext.leanDomainDir)
			t.lakeCommand.set(ext.lakeCommand.convention("lake"))
			t.irFile.set(ext.irFile)
			t.onlyIf { ext.leanRootNamespace.isPresent }
			t.leanSources.from(ext.leanDomainDir.map { dir ->
				project.fileTree(dir) { ft ->
					ft.include("**/*.lean", "lakefile.toml")
					ft.exclude(".lake/**", "build/**")
				}
			})
			t.leanSources.from(ext.leanExtractorDir.map { dir ->
				project.fileTree(dir) { ft ->
					ft.include("**/*.lean", "lakefile.toml")
					ft.exclude(".lake/**")
				}
			})
		}
		project.afterEvaluate {
			if (ext.leanRootNamespace.isPresent) {
				gen.configure { it.dependsOn(extract) }
			}
		}

		// Kotlin JVM プロジェクトへ自動配線(生成ディレクトリの登録とコンパイル依存)
		project.plugins.withId("org.jetbrains.kotlin.jvm") {
			project.afterEvaluate {
				if (ext.wireSourceSets.get()) {
					val sourceSets = project.extensions.getByType(SourceSetContainer::class.java)
					fun kotlinSrc(name: String) =
						((sourceSets.getByName(name) as ExtensionAware).extensions
							.getByName("kotlin") as SourceDirectorySet)
					kotlinSrc("main").srcDir(ext.mainOut)
					kotlinSrc("test").srcDir(ext.testOut)
				}
			}
			project.tasks.matching { it.name == "compileKotlin" || it.name == "compileTestKotlin" }
				.configureEach { it.dependsOn(gen) }
		}
	}
}
