import test from "node:test";
import assert from "node:assert/strict";
import { mkdtempSync, mkdirSync, writeFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { spawnSync } from "node:child_process";

const status = fileURLToPath(new URL("../.apm/skills/cradle/scripts/status.mjs", import.meta.url));

// 一時プロジェクト: 生成された Port の interface と、それを実装する手書きの Adapter（か、Port を受けるだけの UseCase 実装）。
// adapterTest は生成された Adapter 適合テストの有無と、src/adapterTest の具象クラスの有無
function fixture(t, { adapter, useCaseImpl = false, adapterTest = "none" }) {
  const root = mkdtempSync(join(tmpdir(), "cradle-status-port-"));
  t.after(() => rmSync(root, { recursive: true, force: true }));
  writeFileSync(join(root, "cradle.json"), JSON.stringify({ project: "Example" }));
  const gen = join(root, "backend/src/generated/kotlin-main/application/port/directory");
  mkdirSync(gen, { recursive: true });
  writeFileSync(join(gen, "Directory.kt"), "// GENERATED by lean2kotlin — DO NOT EDIT\n\npackage p\n\n/**\n * Lean: Port `Example.Application.Port.Directory`(外部能力)。\n */\ninterface Directory {\n\tfun find(request: DirectoryFindRequest): DirectoryFindOutcome\n}\n");
  writeFileSync(join(gen, "DirectoryFindRequest.kt"), "// GENERATED by lean2kotlin — DO NOT EDIT\n\npackage p\n\n/**\n * Lean: `Example.Application.Port.Directory.Find.Request`(portRequest)\n */\ndata class DirectoryFindRequest(val id: Long)\n");
  const main = join(root, "backend/src/main/kotlin/p/infrastructure/directory");
  mkdirSync(main, { recursive: true });
  if (adapter) writeFileSync(join(main, "HttpDirectory.kt"), "package p\n\nclass HttpDirectory(private val client: Any) : Directory {\n\toverride fun find(request: DirectoryFindRequest): DirectoryFindOutcome = TODO(\"http\")\n}\n");
  if (useCaseImpl) {
    const app = join(root, "backend/src/main/kotlin/p/application/usecase/bookvisit");
    mkdirSync(app, { recursive: true });
    writeFileSync(join(app, "BookVisitUseCaseImpl.kt"), "package p\n\nclass BookVisitUseCaseImpl(\n\tprivate val repo: VisitRepository,\n\tprivate val directory: Directory,\n) : BookVisitUseCase {\n\toverride fun execute(c: BookVisitCommand): Unit = TODO(\"impl\")\n}\n");
  }
  if (adapterTest !== "none") {
    const genAdapter = join(root, "backend/src/generated/kotlin-adapter-test/application/port/directory");
    mkdirSync(genAdapter, { recursive: true });
    writeFileSync(join(genAdapter, "DirectoryAdapterContractTest.kt"), "// GENERATED by lean2kotlin — DO NOT EDIT\n\npackage p\n\nabstract class DirectoryAdapterContractTest {\n\tprotected abstract fun adapter(): Directory\n}\n");
  }
  if (adapterTest === "wired") {
    const at = join(root, "backend/src/adapterTest/kotlin/p");
    mkdirSync(at, { recursive: true });
    writeFileSync(join(at, "DirectoryAdapterContractTestImpl.kt"), "package p\n\nclass DirectoryAdapterContractTestImpl : DirectoryAdapterContractTest() {\n\toverride fun adapter(): Directory = HttpDirectory(Any())\n}\n");
  }
  mkdirSync(join(root, "backend/src/test"), { recursive: true });
  const env = { ...process.env };
  for (const key of ["CRADLE_PROJECT_DIR", "CRADLE_CONFIG", "CLAUDE_PROJECT_DIR"]) delete env[key];
  const r = spawnSync(process.execPath, [status, "--json"], { cwd: root, env, encoding: "utf8", timeout: 20_000 });
  assert.equal(r.status, 0, r.stderr);
  return JSON.parse(r.stdout).phases.find(p => p.name === "バックエンド");
}

test("Port の生成 interface の数と Adapter の数を出し、Adapter が無ければ次の一手にする", (t) => {
  const backend = fixture(t, { adapter: false });
  assert.ok(backend.facts.includes("Port 1 件（Adapter 0）"), backend.facts.join(" / "));
  assert.match(backend.next, /Adapter の無い Port Directory/);
});

test("Port をコンストラクタで受けるだけの UseCase 実装は Adapter と数えない", (t) => {
  const backend = fixture(t, { adapter: false, useCaseImpl: true });
  assert.ok(backend.facts.includes("Port 1 件（Adapter 0）"), backend.facts.join(" / "));
  assert.match(backend.next, /Adapter の無い Port Directory/);
});

test("Adapter があれば Port は揃ったと数える", (t) => {
  const backend = fixture(t, { adapter: true });
  assert.ok(backend.facts.includes("Port 1 件（Adapter 1）"), backend.facts.join(" / "));
  assert.doesNotMatch(backend.next, /Adapter/);
});


test("Adapter 適合テストは契約テストの分母に入れず、src/adapterTest の配線を別に数えて次の一手にする", (t) => {
  const unwired = fixture(t, { adapter: true, adapterTest: "generated" });
  assert.ok(unwired.facts.includes("契約テスト 配線 0/0"), unwired.facts.join(" / "));
  assert.ok(unwired.facts.includes("Port 1 件（Adapter 1、適合テスト 配線 0/1）"), unwired.facts.join(" / "));
  assert.match(unwired.next, /未配線の Adapter 適合テスト 1 件を src\/adapterTest\/kotlin/);
  const wired = fixture(t, { adapter: true, adapterTest: "wired" });
  assert.ok(wired.facts.includes("Port 1 件（Adapter 1、適合テスト 配線 1/1）"), wired.facts.join(" / "));
  assert.doesNotMatch(wired.next, /Adapter/);
  // Adapter が無ければ、適合テストの配線より先に Adapter を書くことを言う
  const noAdapter = fixture(t, { adapter: false, adapterTest: "generated" });
  assert.match(noAdapter.next, /Adapter の無い Port Directory/);
});
