import test from "node:test";
import assert from "node:assert/strict";
import { mkdtempSync, mkdirSync, writeFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { spawnSync } from "node:child_process";

const status = fileURLToPath(new URL("../.apm/skills/cradle/scripts/status.mjs", import.meta.url));

// 一時プロジェクト: 生成された Port の interface と、それを実装する手書きの Adapter（か、Port を受けるだけの UseCase 実装）
function fixture(t, { adapter, useCaseImpl = false }) {
  const root = mkdtempSync(join(tmpdir(), "cradle-status-port-"));
  t.after(() => rmSync(root, { recursive: true, force: true }));
  writeFileSync(join(root, "cradle.json"), JSON.stringify({ project: "Example" }));
  const gen = join(root, "backend/src/generated/kotlin-main/application/port/directory");
  mkdirSync(gen, { recursive: true });
  writeFileSync(join(gen, "Directory.kt"), "// GENERATED by lean2kotlin — DO NOT EDIT\n\npackage p\n\n/**\n * Lean: Port `Example.Application.Port.Directory`(外部能力)。\n */\ninterface Directory {\n\tfun find(request: DirectoryFindRequest): DirectoryFindOutcome\n}\n");
  writeFileSync(join(gen, "DirectoryFindRequest.kt"), "// GENERATED by lean2kotlin — DO NOT EDIT\n\npackage p\n\n/**\n * Lean: `Example.Application.Port.Directory.Find.Request`(portRequest)\n */\ndata class DirectoryFindRequest(val id: Long)\n");
  const main = join(root, "backend/src/main/kotlin/p/infrastructure/directory");
  mkdirSync(main, { recursive: true });
  if (adapter) writeFileSync(join(main, "HttpDirectory.kt"), "package p\n\nclass HttpDirectory(private val client: Any) : Directory {\n\toverride fun find(request: DirectoryFindRequest): DirectoryFindOutcome = TODO(\"http\")\n}\n");
  if (useCaseImpl) {
    const app = join(root, "backend/src/main/kotlin/p/application/usecase/bookvisit");
    mkdirSync(app, { recursive: true });
    writeFileSync(join(app, "BookVisitUseCaseImpl.kt"), "package p\n\nclass BookVisitUseCaseImpl(\n\tprivate val repo: VisitRepository,\n\tprivate val directory: Directory,\n) : BookVisitUseCase {\n\toverride fun execute(c: BookVisitCommand): Unit = TODO(\"impl\")\n}\n");
  }
  mkdirSync(join(root, "backend/src/test"), { recursive: true });
  const env = { ...process.env };
  for (const key of ["CRADLE_PROJECT_DIR", "CRADLE_CONFIG", "CLAUDE_PROJECT_DIR"]) delete env[key];
  const r = spawnSync(process.execPath, [status, "--json"], { cwd: root, env, encoding: "utf8", timeout: 20_000 });
  assert.equal(r.status, 0, r.stderr);
  return JSON.parse(r.stdout).phases.find(p => p.name === "バックエンド");
}

test("Port の生成 interface の数と Adapter の数を出し、Adapter が無ければ次の一手にする", (t) => {
  const backend = fixture(t, { adapter: false });
  assert.ok(backend.facts.includes("Port 1 件（Adapter 0）"), backend.facts.join(" / "));
  assert.match(backend.next, /Adapter の無い Port Directory/);
});

test("Port をコンストラクタで受けるだけの UseCase 実装は Adapter と数えない", (t) => {
  const backend = fixture(t, { adapter: false, useCaseImpl: true });
  assert.ok(backend.facts.includes("Port 1 件（Adapter 0）"), backend.facts.join(" / "));
  assert.match(backend.next, /Adapter の無い Port Directory/);
});

test("Adapter があれば Port は揃ったと数える", (t) => {
  const backend = fixture(t, { adapter: true });
  assert.ok(backend.facts.includes("Port 1 件（Adapter 1）"), backend.facts.join(" / "));
  assert.doesNotMatch(backend.next, /Adapter/);
});
