#!/usr/bin/env node
// unslop-lint — AI が書きがちな「それらしいが価値のない」痕跡と、腐る情報の写しを機械で拾う。
//
//   unslop-lint [--all | --diff | <files>...] [--json]
//     既定は --diff（HEAD との差分 + 未追跡ファイル）。
//
// 規則（cradle.json の unslop.disable で個別に切れる / unslop.extraHedges で語を足せる / unslop.skipFiles で見ないファイル / unslop.ignorePaths で実在しなくてよいパス）:
//   comment-status   [error] コードのコメントにドメイン事実のステータス語（open / resolved / unresolved / 反映済 / 却下 / 未決 / 検証済 / 未検証）
//   comment-domain-id[error] コードに documents の ID（HS-/UX-/MQ-/ADR-/INFRA-/イベント#）— 参照は documents → code の一方向。
//                            例外は Lean モデル（形式化の出典として持てる）。その代わり:
//   lean-ref-missing [error] Lean が引く出典 ID が documents に無い
//   lean-ref-retracted[warn] Lean が引く出典 ID が撤回・却下済み（状態列の値、状態列の無い表では最後の列の先頭で判定）
//   lean-name-unlisted[warn] 形式化が付けた名前（コマンド構成子・失敗語彙・画面の口）に用語集の行が無い（骨格のサンプルの間は見ない）
//   comment-history  [warn]  コードのコメントに日付・経緯（「2026-08-21 に撤回」等）— 経緯は documents の持ち物
//   comment-ai-notes [warn]  コードから ai-notes を根拠として引く — ai-notes は規約ではない
//   todo-bare        [warn]  TODO/FIXME/HACK に理由が無い（TODO(proof): 形式は可）
//   hedge            [warn]  コメント・docstring の逃げ言葉（たぶん/とりあえず/一旦/should work/probably…）
//   empty-catch      [error] 例外を握りつぶす空の catch
//   suppress-no-why  [warn]  @Suppress / eslint-disable / oxlint-disable に理由コメントが無い
//   console-log      [warn]  frontend の本番コードに console.log
//   emoji            [warn]  コードや docstring の装飾絵文字
//   stale-path       [error] コメント・ドキュメントが指すリポジトリ内パスが存在しない（README・CLAUDE.md・.apm/instructions の腐りも拾う）。
//                            ハーネスの散文（配布物の rules / skills / agents・compile された AGENTS.md）は見ない — 消費側は cradle.json で置き場を変えられるので突き合わせられない
//   restate          [warn]  直下の宣言名をそのまま繰り返すだけのコメント
//   ai-note-header   [error] ai-notes の命名（YYYYMMDD-NN-<topic>.md）と冒頭の「規約ではありません」の断り
import { existsSync, readFileSync, statSync } from "node:fs";
import { join, extname, dirname, basename } from "node:path";
import { loadConfig, parseArgs, walk, rel, git, fail, globToRegExp, scaffoldSampleFiles, leanVocabulary, glossaryEnglish, tableRows } from "./lib.mjs";

const opts = parseArgs(process.argv.slice(2), { all: "bool", diff: "bool", json: "bool" });
const cfg = loadConfig();
const disabled = new Set(cfg.unslop.disable ?? []);
const CODE_EXT = [".kt", ".kts", ".ts", ".tsx", ".js", ".mjs", ".lean", ".sql", ".tf", ".css", ".html"];
const DOC_EXT = [".md", ".yaml", ".yml"];
const codeDirs = [cfg.lean.dir, cfg.backend.dir, cfg.frontend.dir, cfg.e2e.dir, cfg.infra.dir].map(d => join(cfg.root, d));
// ハーネスの散文（APM が配る rules / skills / agents と、Codex 向けに compile された AGENTS.md）
const HARNESS_DIRS = [".claude/rules", ".claude/skills", ".claude/agents", ".claude/commands", ".agents/skills"];
const isHarnessProse = (relPath) => HARNESS_DIRS.some(d => relPath.startsWith(d + "/")) || relPath === "AGENTS.md" || relPath.startsWith(".codex/");

function candidateFiles() {
  if (opts._.length) return opts._.map(p => p.startsWith("/") ? p : join(cfg.root, p)).filter(existsSync);
  if (opts.all) {
    const code = codeDirs.flatMap(d => walk(d, { ext: CODE_EXT }));
    // .apm/instructions は消費側の固有の事実の正本（写しの rules / AGENTS.md ではなくここを見る）
    const docs = [...walk(join(cfg.root, cfg.documents.dir), { ext: DOC_EXT }), ...["CLAUDE.md", "README.md", "AGENTS.md"].map(f => join(cfg.root, f)).filter(existsSync),
      ...walk(join(cfg.root, ".apm", "instructions"), { ext: [".md"] }),
      ...codeDirs.flatMap(d => walk(d, { ext: [".md"] })),
      ...HARNESS_DIRS.flatMap(d => walk(join(cfg.root, d), { ext: [".md"] }))];
    return [...new Set([...code, ...docs])];
  }
  let names = [];
  try {
    names = [...git(cfg.root, ["diff", "--name-only", "HEAD"]).split("\n"), ...git(cfg.root, ["ls-files", "--others", "--exclude-standard"]).split("\n")];
  } catch { return []; }
  return [...new Set(names.filter(Boolean))].map(n => join(cfg.root, n)).filter(p => existsSync(p) && statSync(p).isFile());
}

const isGenerated = (path) => /(^|\/)(generated|node_modules|\.lake|build|dist)\//.test(path) || /^\/\/ GENERATED by/.test(readFileSync(path, "utf8").slice(0, 200));

/** 行ごとのコメント本文（無ければ null）。ブロックコメントも行単位に切って返す。 */
function commentLines(text, ext) {
  const lines = text.split("\n");
  const out = [];
  let inBlock = null; // { open, close }
  const style = [".lean"].includes(ext) ? { line: "--", open: "/-", close: "-/" }
    : [".sql"].includes(ext) ? { line: "--", open: "/*", close: "*/" }
    : [".tf"].includes(ext) ? { line: "#", open: "/*", close: "*/" }
    : [".css"].includes(ext) ? { line: null, open: "/*", close: "*/" }
    : [".html"].includes(ext) ? { line: null, open: "<!--", close: "-->" }
    : { line: "//", open: "/*", close: "*/" };
  lines.forEach((l, i) => {
    let s = l;
    if (inBlock) {
      const end = s.indexOf(inBlock.close);
      if (end >= 0) { out.push({ line: i + 1, text: s.slice(0, end), code: s.slice(end + inBlock.close.length) }); inBlock = null; }
      else out.push({ line: i + 1, text: s, code: "" });
      return;
    }
    const openIdx = style.open ? s.indexOf(style.open) : -1;
    const lineIdx = style.line ? s.indexOf(style.line) : -1;
    if (lineIdx >= 0 && (openIdx < 0 || lineIdx < openIdx) && !inString(s, lineIdx)) { out.push({ line: i + 1, text: s.slice(lineIdx + style.line.length), code: s.slice(0, lineIdx) }); return; }
    if (openIdx >= 0 && !inString(s, openIdx)) {
      const end = s.indexOf(style.close, openIdx + style.open.length);
      if (end >= 0) out.push({ line: i + 1, text: s.slice(openIdx + style.open.length, end), code: s.slice(0, openIdx) + s.slice(end + style.close.length) });
      else { out.push({ line: i + 1, text: s.slice(openIdx + style.open.length), code: s.slice(0, openIdx) }); inBlock = style; }
    }
  });
  return out;
}
function inString(line, idx) {
  const before = line.slice(0, idx);
  return (before.match(/"/g) ?? []).length % 2 === 1;
}

const HEDGES = ["たぶん", "おそらく", "とりあえず", "一旦", "仮に", "暫定的に", "多分", "should work", "should be fine", "probably", "maybe", "hopefully", "I think", "for now", "quick fix", "temporary hack", ...(cfg.unslop.extraHedges ?? [])];
const STATUS = /\b(open|resolved|unresolved)\b|反映済|却下|未決|検証済|未検証/;
const DOMAIN_ID = /\b(HS|UX|MQ|ADR|INFRA-[DAQ]|L2K-Q|FE-Q)-\d{3}\b|イベント#\d+/;
const HISTORY = /(?:20\d{2}-\d{2}-\d{2}|20\d{6}(?:-\d{2})?)\s*(?:に|の|時点|版|裁定|改訂|移行|決定|撤回)|に撤回|に改訂|に廃止|に確定|の経緯|議論の結果|裁定/;
const EMOJI = /[\u{1F300}-\u{1FAFF}\u{2600}-\u{27BF}\u{2B50}\u{2705}\u{274C}]/u;
// 拡張子の後ろにさらに拡張子が続くもの（foo.md.tmpl）は別のファイルなので、途中の .md で切って拾わない
const PATH_IN_TEXT = /(?<![\w@/.$-])((?:[A-Za-z0-9_.-]+\/)+[A-Za-z0-9_.-]+\.(?:kt|kts|ts|tsx|js|mjs|lean|md|ya?ml|sql|json|tf|html|css|toml|sh))(?![\w/-]|\.\w)/g;

/** ルート相対・ファイルの祖先相対・プロジェクト内ファイルのサフィックス一致のいずれかで実在すれば腐っていない。 */
let allProjectFiles = null;
function pathExistsSomewhere(p, fromFile) {
  if (existsSync(join(cfg.root, p))) return true;
  let d = dirname(fromFile);
  for (;;) {
    if (existsSync(join(d, p))) return true;
    if (d === cfg.root || d === dirname(d)) break;
    d = dirname(d);
  }
  if (!allProjectFiles) allProjectFiles = walk(cfg.root, { ext: null }).map(f => rel(cfg.root, f));
  const suffix = "/" + p;
  return allProjectFiles.some(f => f.endsWith(suffix) || f === p);
}

/** documents の ID 台帳: ID → { cells, columns, statusIdx }。columns は表の見出し、statusIdx は `状態` / `状況` 列の位置（無い表は null）。 */
let ledger = null;
function lookupId(id) {
  if (!ledger) {
    ledger = new Map();
    for (const f of walk(join(cfg.root, cfg.documents.dir), { ext: [".md"] })) {
      for (const r of tableRows(readFileSync(f, "utf8"))) {
        const idx = r.columns.findIndex(c => c === "状態" || c === "状況");
        const entry = { cells: r.cells, columns: r.columns, statusIdx: idx < 0 ? null : idx };
        const first = r.cells[0] ?? "";
        if (/^(?:HS|UX|MQ|ADR|INFRA-[DAQ])-\d{3}$/.test(first) && !ledger.has(first)) ledger.set(first, entry);
        if (/event-timeline/.test(f) && /^\d+(?:\.\d+)?[a-z]?$/.test(first)) ledger.set(`イベント#${first}`, entry);
      }
    }
  }
  return ledger.get(id) ?? null;
}

/** 撤回・却下の判定。状態列があればその値が `撤回` / `却下` で始まるとき、無い表では最後の列（見出しで決める）の先頭が `撤回:` のとき。見た列と値を返す。 */
function retractedBy(entry) {
  if (entry.statusIdx !== null) {
    const value = entry.cells[entry.statusIdx] ?? "";
    return /^(撤回|却下)/.test(value) ? `${entry.columns[entry.statusIdx]}: ${value}` : null;
  }
  const idx = entry.columns.length - 1;
  const value = entry.cells[idx] ?? "";
  return /^撤回[:：]/.test(value) ? `${entry.columns[idx]}: ${value}` : null;
}

/** 実在しなくて当然のパス: ビルド成果物・一時ファイル・cradle.json の unslop.ignorePaths（glob）。 */
const IGNORED_PATHS = [/^(build|dist|node_modules|\.lake|target|out)\//, /\/(build|dist|node_modules|\.lake|target)\//, /questions\.md$/, /naming\.md$/, /\.session$/, /(^|\/)lake-manifest\.json$/,
  ...((cfg.unslop.ignorePaths ?? []).map(globToRegExp))];

const findings = [];
const add = (rule, severity, file, line, message) => { if (!disabled.has(rule)) findings.push({ rule, severity, file: rel(cfg.root, file), line, message }); };

// APM が生成する lockfile は配布物のパス一覧で、散文ではない
const SKIP_FILES = ["apm.lock.yaml", ...(cfg.unslop.skipFiles ?? [])].map(globToRegExp);
const files = candidateFiles();
for (const file of files) {
  const relPath = rel(cfg.root, file);
  if (SKIP_FILES.some(re => re.test(relPath))) continue;
  const ext = extname(file);
  if (!CODE_EXT.includes(ext) && !DOC_EXT.includes(ext)) continue;
  if (relPath.startsWith(cfg.documents.dir + "/") && !DOC_EXT.includes(ext)) continue;
  let text;
  try { text = readFileSync(file, "utf8"); } catch { continue; }
  if (CODE_EXT.includes(ext) && isGenerated(file)) continue;
  const isDoc = DOC_EXT.includes(ext);
  const isDdd = relPath.startsWith(cfg.documents.dir + "/");
  const lines = text.split("\n");

  // stale-path: コード・ドキュメントの両方（documents は正本なので ID は書いてよいが、パスの腐りは拾う）。
  // ハーネスの散文は見ない — 配布物が指すパスは消費側の cradle.json で置き場が変わり、消費側のツリーとは突き合わせられない
  if (!isHarnessProse(relPath)) lines.forEach((l, i) => {
    for (const m of l.matchAll(PATH_IN_TEXT)) {
      const p = m[1];
      if (/^(https?:|\$|\{|<)/.test(p) || p.includes("*") || p.includes("{") || p.includes("<")) continue;
      if (IGNORED_PATHS.some(re => re.test(p))) continue;
      if (!pathExistsSomewhere(p, file)) add("stale-path", "error", file, i + 1, `存在しないパスを指しています: ${p}`);
    }
  });

  if (isDoc && relPath.startsWith(cfg.documents.aiNotes + "/") && !relPath.endsWith("README.md") && !relPath.endsWith("TEMPLATE.md")) {
    const name = relPath.slice(cfg.documents.aiNotes.length + 1);
    if (!/^\d{8}-\d{2}-[a-z0-9-]+\.md$/.test(name)) add("ai-note-header", "error", file, 1, `ファイル名は YYYYMMDD-NN-<topic>.md（${name}）`);
    if (!/規約ではありません/.test(text.slice(0, 800))) add("ai-note-header", "error", file, 1, "冒頭に「これは規約ではありません。」の断りが無い");
  }
  if (isDoc) {
    // ドキュメント側は文体の規則だけ（ID・ステータスは正本の持ち物）
    if (!isDdd) lines.forEach((l, i) => { if (EMOJI.test(l) && !/^\|/.test(l.trim())) add("emoji", "warn", file, i + 1, "装飾の絵文字"); });
    continue;
  }

  const comments = commentLines(text, ext);
  for (const c of comments) {
    const t = c.text;
    if (STATUS.test(t) && !/@\[|deriving|def |theorem /.test(t)) add("comment-status", "error", file, c.line, "コメントにドメイン事実のステータス語 — 可変の状態を 2 か所に持たない");
    if (DOMAIN_ID.test(t)) {
      if (ext === ".lean") {
        for (const m of t.matchAll(/\b((?:HS|UX|MQ|ADR|INFRA-[DAQ])-\d{3})\b|(イベント#\d+(?:\.\d+)?[a-z]?)/g)) {
          const id = m[1] ?? m[2];
          const row = lookupId(id);
          if (!row) add("lean-ref-missing", "error", file, c.line, `出典 ${id} が documents に見当たらない — 実在しない記述の引用`);
          else { const by = retractedBy(row); if (by) add("lean-ref-retracted", "warn", file, c.line, `出典 ${id} は撤回・却下されている（${by}）— 根拠が消えたまま残っていないか確かめる`); }
        }
      } else add("comment-domain-id", "error", file, c.line, "コードから documents の ID を引いている — 参照は documents → code の一方向（Lean モデルだけが出典を持てる）");
    }
    if (HISTORY.test(t)) add("comment-history", "warn", file, c.line, "コメントに日付・経緯 — 経緯は documents（ai-notes / ddd）の持ち物");
    if (/ai-notes/.test(t)) add("comment-ai-notes", "warn", file, c.line, "ai-notes を根拠に引いている — ai-notes は規約ではない");
    const todo = t.match(/\b(TODO|FIXME|HACK|XXX)\b(.*)/);
    if (todo && !/^\s*\([^)]+\)\s*:/.test(todo[2]) && !/^\s*\(/.test(todo[2])) add("todo-bare", "warn", file, c.line, `${todo[1]} に理由が無い（TODO(理由): の形にする）`);
    for (const h of HEDGES) if (t.toLowerCase().includes(h.toLowerCase())) { add("hedge", "warn", file, c.line, `逃げ言葉「${h}」— 決まっていないなら実装せず問いに戻す`); break; }
    if (EMOJI.test(t)) add("emoji", "warn", file, c.line, "コメントの装飾絵文字");
  }

  // restate: コメントの直下の宣言名をそのまま繰り返している
  for (const c of comments) {
    const next = lines[c.line]; // 次の行（0-based で c.line）
    if (!next || c.code.trim()) continue;
    const decl = next.match(/\b(?:fun|val|var|class|interface|object|def|theorem|structure|inductive|function|const|let|export)\s+`?([A-Za-z_][\w.]*)/);
    if (!decl) continue;
    const words = c.text.trim().replace(/[.:。]/g, "").split(/\s+/);
    if (words.length <= 2 && words.some(w => w === decl[1] || w.toLowerCase() === decl[1].toLowerCase())) add("restate", "warn", file, c.line, `宣言名を繰り返すだけのコメント（${decl[1]}）`);
  }

  // 言語別
  if ([".kt", ".kts", ".ts", ".tsx", ".js", ".mjs"].includes(ext)) {
    let inRaw = false;   // Kotlin の raw string（"""）の中は検査しない（テストの fixture・文言）
    lines.forEach((l, i) => {
      const rawMarks = (l.match(/"""/g) ?? []).length;
      const wasRaw = inRaw;
      if (rawMarks % 2 === 1) inRaw = !inRaw;
      if (wasRaw || (rawMarks && inRaw)) return;
      if (/catch\s*\([^)]*\)\s*\{\s*\}/.test(l) || (/catch\s*\([^)]*\)\s*\{\s*$/.test(l) && /^\s*\}\s*$/.test(lines[i + 1] ?? ""))) add("empty-catch", "error", file, i + 1, "空の catch — 失敗を握りつぶしている");
      const sup = l.match(/@Suppress\(|eslint-disable|oxlint-disable|@ts-ignore|@ts-expect-error/);
      if (sup && !/["']/.test(l.slice(0, sup.index))) {
        const prev = lines[i - 1] ?? "";
        const hasWhy = /\/\/|\/\*/.test(l) || /^\s*(\/\/|\*|\/\*)/.test(prev);
        if (!hasWhy) add("suppress-no-why", "warn", file, i + 1, "抑止に理由コメントが無い");
      }
      if (/console\.(log|debug)\(/.test(l) && relPath.startsWith(cfg.frontend.dir + "/src/") && !/\.test\.|\/test\//.test(relPath)) add("console-log", "warn", file, i + 1, "本番コードの console.log");
    });
  }
}

// lean-name-unlisted: 形式化が付けた名前に用語集の行があるか。骨格のサンプルが残る間は名前もサンプルなので見ない
{
  const named = leanVocabulary(cfg).filter(v => files.includes(v.file));
  if (named.length && !scaffoldSampleFiles(cfg).length) {
    const glossary = glossaryEnglish(cfg);
    for (const v of named) {
      if (glossary.has(v.name.toLowerCase())) continue;
      add("lean-name-unlisted", "warn", v.file, v.line, `用語集に「${v.name}」の行が無い（${v.kind}${v.doc ? `。暫定: ${v.doc}` : ""}）— 次の探索セッションで用語と英語候補を確かめる`);
    }
  }
}

findings.sort((a, b) => a.file.localeCompare(b.file) || a.line - b.line);
if (opts.json) console.log(JSON.stringify({ findings }, null, 2));
else {
  for (const f of findings) console.log(`${f.severity.padEnd(5)} ${f.rule.padEnd(17)} ${f.file}:${f.line}  ${f.message}`);
  const e = findings.filter(f => f.severity === "error").length;
  console.log(`\n${findings.length} findings (${e} error, ${findings.length - e} warn)`);
}
process.exit(findings.some(f => f.severity === "error") ? 1 : 0);
